module.exports = {
  apps: [
    {
      name: 'api',
      cwd: '/root/PRICELIO/services/api',
      script: 'src/index.js',
      env_file: '/root/PRICELIO/services/api/.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
    {
      name: 'ai-gateway',
      cwd: '/root/PRICELIO/services/ai-gateway',
      script: 'src/index.js',
      env_file: '/root/PRICELIO/services/ai-gateway/.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'receipts',
      cwd: '/root/PRICELIO/services/receipts',
      script: 'src/worker.js',
      env_file: '/root/PRICELIO/services/receipts/.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'ingest',
      cwd: '/root/PRICELIO/services/ingest',
      script: 'src/index.js',
      env_file: '/root/PRICELIO/services/ingest/.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'analytics',
      cwd: '/root/PRICELIO/services/analytics',
      script: 'src/index.js',
      env_file: '/root/PRICELIO/services/analytics/.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'admin',
      cwd: '/root/PRICELIO/apps/admin',
      script: 'server.js',
      env_file: '/root/PRICELIO/apps/admin/.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'frontend',
      cwd: '/root/PRICELIO',
      script: '-m http.server 8080',
      interpreter: 'python3',
      instances: 1,
      autorestart: true,
      watch: false,
    },
  ],
};
